#!/bin/bash

if command -v vim >/dev/null 2>&1; then
  echo "Bootstraping Vim"
    if [ ! -f "$HOME/.vim/autoload/plug.vim" ]; then
      echo "Installing Vim Plug ..."
      curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi

  curl https://raw.githubusercontent.com/joeltaylor/Smyck-Color-Scheme/master/smyck.vim \
    --create-dirs -o ~/.vim/colors/smyck.vim
  vim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi

if [ ! -d ~/.tmux/plugins/tpm ]; then
    echo "Cloning tpm"
    git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
    echo "Installing tmux plugins"
    ~/.tmux/plugins/tpm/bin/install_plugins
fi

